name: 'Prestige Living Blog '
favicon: null
layout_spectrum: 0.049051869893446565
typography_spectrum: 0.4495193453039974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6547667258419096
  lightness: 0.34979545534588397
  saturation: 0.9385678148828447
  rhythmicContrast: 0.20423001353628933
purpose: []
