typography_spectrum: 0.8939005536958575
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.13428064086474478
  lightness: 0.09904017625376582
  saturation: 0.539568800944835
  rhythmicContrast: 0.40294672758318484
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1817944562062621
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Kyriacos C.Kolokasides
  email: k.kolokasides@gmail.com
name: 'Prestige Living Blog '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: All about quality lifestyle
purpose: []
