name: 'Prestige Living Blog '
opengraph:
  image: null
  type: null
  appId: null
author:
  name: Kyriacos C.Kolokasides
  email: k.kolokasides@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.1817944562062621
color:
  saturation: 0.539568800944835
  brandStrength: 0.1342806408647448
  rhythmicContrast: 0.4029467275831848
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  lightness: 0.09904017625376582
cta:
  bucket: null
  version: null
  domain: null
title: All about quality lifestyle
purpose: []
favicon: null
typography_spectrum: 0.8939005536958575
analytics:
  twitter: null
  google: null
  facebook: null
