typography_spectrum: 0.8939005536958575
content_rating:
  adult: true
color:
  saturation: 0.539568800944835
  brandStrength: 1
  lightness: 0.09904017625376582
  brandColors:
    - '#F4F3EF'
    - '#292929'
    - '#8C7C62'
    - '#090408'
    - '#AAA9AE'
  rhythmicContrast: 0.4029467275831848
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1817944562062621
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Kyriacos C.Kolokasides
  email: k.kolokasides@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8ff551e6-80b9-4e49-886c-2ba057c5bc7e.png
name: 'Prestige Living Blog '
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: All about quality lifestyle
purpose: []
